/** Nakładka EN na src/content/common/pl.js (te same klucze). */
const common = {
  skipLink: 'Skip to content',
  homeAria: 'AS COMPANY POLAND – home page',
  mainNavAria: 'Main navigation',
  book: 'Book a visit',
  menuOpen: 'Open menu',
  menuClose: 'Close menu',
  menuAria: 'Menu',
  shortcutsAria: 'Shortcuts',
  languageAria: 'Language',
  more: 'More',
  less: 'Less',
  close: 'Close',
  rights: 'All rights reserved.',
  privacy: 'Privacy Policy',
  nip: 'Tax ID (NIP)',
  stickyTraining: 'Training',
  goTo: 'Go to:',
  closingLabel: 'Contact',
  requiredLegend: 'Fields marked * are required.',
  noticeController: 'The data controller is',
  noticePurpose: 'We process the data from this form to answer your enquiry and, if you ask us to, to prepare an offer.',
  noticeTerms: { pre: 'The rules for using the forms are set out in our ', link: 'Terms of Use', post: '.' },
  bookingPurpose:
    'We process the data from this form to book and handle your appointment; the appointment and your contact details are saved in the salon’s Google Calendar.',
  bookingTerms: {
    pre: 'By clicking “{button}”, you accept our ',
    link: 'Terms of Use',
    post: ' – points 9–10 describe how booking works and how to change or cancel a visit.',
  },
  bookingTurnstile: { pre: 'The form is protected by Cloudflare Turnstile – see the ', link: 'Cookie Policy', post: ' for details.' },
  documents: 'Documents',
  cookiesPolicy: 'Cookie Policy',
  terms: 'Terms of Use',
  cookieSettings: 'Cookie settings',
  notFound: {
    metaTitle: 'Page not found',
    label: 'Not found',
    title: 'This page',
    accent: 'does not exist.',
    body: 'The address may have changed or the page may have been moved. Start from the home page or write to us – we will help you find what you are looking for.',
    home: 'Home page',
    contact: 'Contact',
  },
};

export default common;
